// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-t6xKL9yY1Q0yCTrlZPPzOoPJcMrY9fQ',
    appId: '1:411358792205:web:f962bb248172fe8c85e344',
    messagingSenderId: '411358792205',
    projectId: 'bizworks-12327',
    authDomain: 'bizworks-12327.firebaseapp.com',
    storageBucket: 'bizworks-12327.appspot.com',
    measurementId: 'G-1YE2T9LP9T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBXlAmmDjtNPjx2cdMwaBV0iy82Af3CF4',
    appId: '1:411358792205:android:4d24df9a5241af0185e344',
    messagingSenderId: '411358792205',
    projectId: 'bizworks-12327',
    storageBucket: 'bizworks-12327.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBa97ysPFAY8T7vJQ-rLtBgdYxGFnFniGg',
    appId: '1:411358792205:ios:62491253f92e8c1d85e344',
    messagingSenderId: '411358792205',
    projectId: 'bizworks-12327',
    storageBucket: 'bizworks-12327.appspot.com',
    iosClientId: '411358792205-95v3p2fol6lcfd237p43hm3tckhdjokq.apps.googleusercontent.com',
    iosBundleId: 'tw.com.bizworks.dispatch',
  );
}
